name: libssh_binding
description: binding and high-level wrapper on top of libssh - The SSH library! libssh is a multiplatform C library implementing the SSHv2 protocol on client and server side. With libssh, you can remotely execute programs, transfer files, use a secure and transparent tunnel https://www.libssh.org
#publish_to: 'none' 
version: 1.0.0
repository: https://github.com/insinfo/libssh_binding
homepage: https://github.com/insinfo/libssh_binding

environment:
  sdk: ">=2.13.1 <3.0.0"

dependencies:
  ffi: ^1.1.2
  path: ^1.8.0

dev_dependencies: 
  build_runner: any
  ffigen: ^4.1.2 #^4.0.0
  #win32: ^2.2.9


ffigen:
  name: 'test'
  description: 'Bindings to test'
  output: 'test.dart'
  llvm-path:     
    - 'C:\Program Files\llvm'      
  headers:
    entry-points:
      #- 'libssh/include/libssh/sftp.h'     
      - 'extra/test.h' 
    #include-directives:
      #- '**sftp.h'
      #- 'libssh/include/libssh/**'
      #- 'libssh/src/**'
  #compiler-opts:
    #- '-Ilibssh/'